name: Simple Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Display Python version
        run: python --version
      
      - name: Check environment
        run: |
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          ls -la
          
      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Run minimal test
        run: |
          echo "Running minimal test"
          python -c "print('Test successful!')" 